# https://www.docker.com/blog/how-to-dockerize-react-app/
# Using the node docker image.
FROM node:24-alpine

# Make the working directory inside the container
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Move the rest of the files into the container.
COPY . .

# Open up the port. TODO: flexible exposed port.
EXPOSE 3000

# Start the app.
CMD ["npm", "start"]